apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: depscloud-system
  name: gateway
  labels:
    app: depscloud
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      - name: service-precheck
        image: mjpitz/service-precheck:latest
        imagePullPolicy: Always
        args:
        - "extractor"
        - "tracker"
      containers:
      - name: gateway
        image: depscloud/gateway:0.0.5
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  namespace: depscloud-system
  name: gateway
  labels:
    app: depscloud
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
